service:
  name: ${self:custom.serviceName}

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  profile: default

  usagePlan:
    quota:
      limit: 100
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 100
      rateLimit: 50

custom:
  serviceName: image-resizing2
  stage: ${opt:stage, self:custom.defaultStage}
  bucket: dynamic-image-resizing4
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  defaultStage: dev
  stages:
    - ${opt:stage}
    - dev
    - integration
    - production

functions:
  resize:
    handler: src/handlers/resizer/index.handler
    events:
      - http:
          path: /{image}
          method: get
    environment:
      # Provide your bucket name here
      BUCKET: dynamic-image-resizing4
      REGION: eu-central-1
    # layers:
    #   - {Ref: ImageLibsLambdaLayer}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: "arn:aws:s3:::dynamic-image-resizing4/*"
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
        Resource: "arn:aws:s3:::dynamic-image-resizing4/*"

package:
  exclude:
    - layer/**
    - node_modules/**
    - '!node_modules/babel-runtime/**'
    - '!node_modules/sharp/**'

# layers:
#   imageLibs:
#     path: layer
#     compatibleRuntimes:
#       - nodejs10.x
